[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://*.shopify.com https://*.myshopify.com https://craftons.com.au;"
    Access-Control-Allow-Origin = "*" 